###### 2D Numpy Scrapbook

In [1]:
a = [[4,3],[1,2]]

In [2]:
a

[[4, 3], [1, 2]]

In [3]:
a[0][1]

3

In [4]:
size(a)

NameError: name 'size' is not defined

In [5]:
type(a)

list

In [6]:
len(a)

2

In [9]:
b = np.array(a)

In [8]:
import numpy as np

In [10]:
b

array([[4, 3],
       [1, 2]])

In [11]:
b.ndim

2

In [12]:
b.shape

(2, 2)

In [13]:
a.size

AttributeError: 'list' object has no attribute 'size'

In [14]:
b.size

4

In [15]:
c = b*b

In [16]:
c

array([[16,  9],
       [ 1,  4]])

In [17]:
d = np.dot(b,b)

In [18]:
d

array([[19, 18],
       [ 6,  7]])